spring:
  application:
    name: multiplication
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:multiplication;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    include-message: always
    include-binding-errors: always
