spring:
  application:
    name: multiplication
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:file:C:/temp/multiplication;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Forces dialect
cors:
  allowed-origins: http://localhost:4200
server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE
service:
  gamification:
    host: http://localhost:8081

